# -*- coding: utf-8 -*-
"""Well log Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_2v_oiROf6kIxd7OaqOrc4n85SSVCLa
"""

# Import  the Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#!pip install lasio
import lasio

#Read the data
data=lasio.read("15-9-19_SR_COMP_logdata.LAS")
dataset=data.df()

#Visual of top 5 data set
dataset.head()

"""Detail

AC for acoustic compressional slowness

CALI for borehole caliper

DEN for bulk density

GR for gamma ray

NEU for neutron porosity

RDEP for deep resisitivity

RMED for medium resistivity
"""

#Replace DEPT AS DEPTH FOR beter understanding
dataset.rename(columns={"DEPT":"DEPTH"},inplace=True)

#changes to the original dataframe object.
dataset.reset_index(inplace=True)
dataset.head()

#Creating subplot
fig=plt.figure(figsize=(10,10))
#set up the plot axis
ax1=plt.subplot2grid((1,3),(0,0),rowspan=1,colspan=1)
#plot the data
ax1.plot("GR", "DEPTH", data =dataset, color = "green")
ax1.set_xlabel("Gamma") # assign the track
ax1.set_xlim(0,200) # limit of the curve
ax1.set_ylim(4700,3500) # depth limit
ax1.grid() # grid

#Adding Resistivity Plot
ax2=plt.subplot2grid((1,3),(0,1),rowspan=1,colspan=1)
ax2.plot("RDEP","DEPTH",data=dataset,color="red")
ax2.set_xlabel("Deep Resistivity")
ax2.set_xlim(0.2,2000)
ax2.semilogx()  # Resistivity log plot on semilog paper
#ax2.set_ylim(4700,3500)
ax2.grid()

#Adding the density log
ax3=plt.subplot2grid((1,3),(0,2),rowspan=1,colspan=1)
ax3.plot("DEN","DEPTH",data=dataset,color="blue")
ax3.set_xlabel("Density")
ax3.set_xlim(1.95,2.95)
#ax3.set_ylim(4700,3500)
ax3.grid()#Reducing the space between track due to depth level
for i in [ax2,ax3]:
    plt.setp(i.get_yticklabels(), visible=False)





